package live2d;

import haxe.Json;
import sys.io.File;
import sys.FileSystem;

/**
 * `haxelib run live2d-haxe` CLI tool.
 *
 * Provides utilities for working with Live2D model3.json files:
 *  - `--gen-constants` generates a Haxe constants class from model3.json
 *  - `--gen-asset-list` lists all referenced asset files
 *  - `--validate` checks that referenced files exist on disk
 *
 * Usage:
 *   haxelib run live2d-haxe --gen-constants path/to/Haru.model3.json HaruConstants.hx HaruConstants
 *   haxelib run live2d-haxe --gen-asset-list path/to/Haru.model3.json
 *   haxelib run live2d-haxe --validate path/to/Haru.model3.json
 */
class CLI
{
    static function main()
    {
        var args = Sys.args();
        if (args.length == 0)
        {
            printUsage();
            return;
        }

        // When run via `haxelib run`, the last arg is the calling directory.
        // Haxelib sets CWD to the haxelib's classPath, so we need to pop it.
        // (The Haxe compiler passes the CWD as the last argument for `haxelib run`.)
        var cwd = Sys.getCwd();
        if (args.length > 0)
        {
            var last = args[args.length - 1];
            // Heuristic: if the last arg is an existing directory, treat it as CWD
            if (FileSystem.exists(last) && FileSystem.isDirectory(last))
            {
                cwd = last;
                args.pop();
                Sys.setCwd(cwd);
            }
        }

        if (args.length == 0)
        {
            printUsage();
            return;
        }

        var cmd = args[0];
        switch (cmd)
        {
            case "--gen-constants":
                if (args.length < 2)
                {
                    Sys.println("Usage: --gen-constants <model3.json> [output.hx] [ClassName] [package]");
                    return;
                }
                genConstants(
                    args[1],
                    args.length > 2 ? args[2] : null,
                    args.length > 3 ? args[3] : "GeneratedModelConstants",
                    args.length > 4 ? args[4] : null
                );
            case "--gen-asset-list":
                if (args.length < 2)
                {
                    Sys.println("Usage: --gen-asset-list <model3.json>");
                    return;
                }
                genAssetList(args[1]);
            case "--validate":
                if (args.length < 2)
                {
                    Sys.println("Usage: --validate <model3.json>");
                    return;
                }
                validate(args[1]);
            case "--help", "-h":
                printUsage();
            default:
                Sys.println('Unknown command: $cmd');
                printUsage();
        }
    }

    static function printUsage():Void
    {
        Sys.println("live2d-haxe CLI");
        Sys.println("");
        Sys.println("Commands:");
        Sys.println("  --gen-constants <model3.json> [output.hx] [ClassName] [package]");
        Sys.println("      Generate a Haxe constants class from model3.json.");
        Sys.println("      Outputs to stdout if output.hx is omitted.");
        Sys.println("  --gen-asset-list <model3.json>");
        Sys.println("      List all asset files referenced by model3.json.");
        Sys.println("  --validate <model3.json>");
        Sys.println("      Check that all referenced asset files exist on disk.");
        Sys.println("  --help, -h");
        Sys.println("      Show this help.");
    }

    // ===== Commands =====

    static function genConstants(model3Path:String, ?outPath:String, className:String, ?packageName:String):Void
    {
        var content = File.getContent(model3Path);
        var json = Json.parse(content);
        var sb = new StringBuf();

        if (packageName != null && packageName != "")
        {
            sb.add('package $packageName;\n\n');
        }

        sb.add('/**\n');
        sb.add(' * Auto-generated by `haxelib run live2d-haxe --gen-constants`.\n');
        sb.add(' * Source: $model3Path\n');
        sb.add(' */\n');
        sb.add('class $className\n');
        sb.add('{\n');

        // Motions: object with group names as keys
        if (json.FileReferences != null && json.FileReferences.Motions != null)
        {
            var used = new Map<String, Bool>();
            var fields:Array<String> = [];
            for (groupName in Reflect.fields(json.FileReferences.Motions))
            {
                var safe = sanitizeName(groupName, used);
                fields.push('$safe: "$groupName"');
            }
            if (fields.length > 0)
            {
                sb.add('    public static var Motions = { ${fields.join(", ")} };\n');
            }
        }

        // Expressions: array of {Name, File}
        if (json.FileReferences != null && json.FileReferences.Expressions != null)
        {
            var used = new Map<String, Bool>();
            var fields:Array<String> = [];
            for (expr in cast(json.FileReferences.Expressions, Array<Dynamic>))
            {
                if (expr.Name == null) continue;
                var safe = sanitizeName(expr.Name, used);
                fields.push('$safe: "${expr.Name}"');
            }
            if (fields.length > 0)
            {
                sb.add('    public static var Expressions = { ${fields.join(", ")} };\n');
            }
        }

        // HitAreas: array of {Id, Name} (top-level, not under FileReferences)
        if (json.HitAreas != null)
        {
            var used = new Map<String, Bool>();
            var fields:Array<String> = [];
            for (area in cast(json.HitAreas, Array<Dynamic>))
            {
                if (area.Name == null) continue;
                var safe = sanitizeName(area.Name, used);
                fields.push('$safe: "${area.Name}"');
            }
            if (fields.length > 0)
            {
                sb.add('    public static var HitAreas = { ${fields.join(", ")} };\n');
            }
        }

        // Groups: array of {Target, Name, Ids}
        if (json.Groups != null)
        {
            var used = new Map<String, Bool>();
            var fields:Array<String> = [];
            for (grp in cast(json.Groups, Array<Dynamic>))
            {
                if (grp.Name == null) continue;
                var safe = sanitizeName(grp.Name, used);
                fields.push('$safe: "${grp.Name}"');
            }
            if (fields.length > 0)
            {
                sb.add('    public static var Groups = { ${fields.join(", ")} };\n');
            }
        }

        // Textures: array of strings
        if (json.FileReferences != null && json.FileReferences.Textures != null)
        {
            var texArr:Array<String> = [];
            for (tex in cast(json.FileReferences.Textures, Array<Dynamic>))
            {
                texArr.push('"$tex"');
            }
            if (texArr.length > 0)
            {
                sb.add('    public static var Textures = [ ${texArr.join(", ")} ];\n');
            }
        }

        sb.add('}\n');

        if (outPath == null)
        {
            Sys.print(sb.toString());
        }
        else
        {
            File.saveContent(outPath, sb.toString());
            Sys.println('Generated: $outPath');
        }
    }

    static function genAssetList(model3Path:String):Void
    {
        var content = File.getContent(model3Path);
        var json = Json.parse(content);

        if (json.FileReferences != null)
        {
            if (json.FileReferences.Moc != null) Sys.println(json.FileReferences.Moc);
            if (json.FileReferences.Textures != null)
            {
                for (t in cast(json.FileReferences.Textures, Array<Dynamic>)) Sys.println(t);
            }
            if (json.FileReferences.Physics != null && json.FileReferences.Physics != "")
                Sys.println(json.FileReferences.Physics);
            if (json.FileReferences.Pose != null && json.FileReferences.Pose != "")
                Sys.println(json.FileReferences.Pose);
            if (json.FileReferences.Expressions != null)
            {
                for (e in cast(json.FileReferences.Expressions, Array<Dynamic>))
                {
                    if (e.File != null) Sys.println(e.File);
                }
            }
            if (json.FileReferences.Motions != null)
            {
                for (groupName in Reflect.fields(json.FileReferences.Motions))
                {
                    var group = Reflect.field(json.FileReferences.Motions, groupName);
                    var files = Reflect.field(group, "File");
                    if (files != null && Std.isOfType(files, Array))
                    {
                        for (f in cast(files, Array<Dynamic>)) Sys.println(f);
                    }
                    else if (files != null)
                    {
                        Sys.println(files);
                    }
                }
            }
            if (json.FileReferences.UserData != null && json.FileReferences.UserData != "")
                Sys.println(json.FileReferences.UserData);
        }
    }

    static function validate(model3Path:String):Void
    {
        if (!FileSystem.exists(model3Path))
        {
            Sys.println('ERROR: File not found: $model3Path');
            Sys.exit(1);
            return;
        }

        var content = File.getContent(model3Path);
        var json;
        try
        {
            json = Json.parse(content);
        }
        catch (e:Dynamic)
        {
            Sys.println('ERROR: Invalid JSON: $e');
            Sys.exit(1);
            return;
        }

        var dir = haxe.io.Path.directory(model3Path);
        var errors = 0;

        if (json.FileReferences != null)
        {
            if (json.FileReferences.Moc != null)
            {
                if (!FileSystem.exists(dir + "/" + json.FileReferences.Moc))
                {
                    Sys.println('MISSING: ' + json.FileReferences.Moc);
                    errors++;
                }
            }
            if (json.FileReferences.Textures != null)
            {
                for (t in cast(json.FileReferences.Textures, Array<Dynamic>))
                {
                    if (!FileSystem.exists(dir + "/" + t))
                    {
                        Sys.println('MISSING: ' + t);
                        errors++;
                    }
                }
            }
            if (json.FileReferences.Physics != null && json.FileReferences.Physics != "")
            {
                if (!FileSystem.exists(dir + "/" + json.FileReferences.Physics))
                {
                    Sys.println('MISSING: ' + json.FileReferences.Physics);
                    errors++;
                }
            }
            if (json.FileReferences.Pose != null && json.FileReferences.Pose != "")
            {
                if (!FileSystem.exists(dir + "/" + json.FileReferences.Pose))
                {
                    Sys.println('MISSING: ' + json.FileReferences.Pose);
                    errors++;
                }
            }
            if (json.FileReferences.Expressions != null)
            {
                for (e in cast(json.FileReferences.Expressions, Array<Dynamic>))
                {
                    if (e.File != null && !FileSystem.exists(dir + "/" + e.File))
                    {
                        Sys.println('MISSING: ' + e.File);
                        errors++;
                    }
                }
            }
            if (json.FileReferences.Motions != null)
            {
                for (groupName in Reflect.fields(json.FileReferences.Motions))
                {
                    var group = Reflect.field(json.FileReferences.Motions, groupName);
                    var files = Reflect.field(group, "File");
                    if (files != null && Std.isOfType(files, Array))
                    {
                        for (f in cast(files, Array<Dynamic>))
                        {
                            if (!FileSystem.exists(dir + "/" + f))
                            {
                                Sys.println('MISSING: ' + f);
                                errors++;
                            }
                        }
                    }
                    else if (files != null)
                    {
                        if (!FileSystem.exists(dir + "/" + files))
                        {
                            Sys.println('MISSING: ' + files);
                            errors++;
                        }
                    }
                }
            }
            if (json.FileReferences.UserData != null && json.FileReferences.UserData != "")
            {
                if (!FileSystem.exists(dir + "/" + json.FileReferences.UserData))
                {
                    Sys.println('MISSING: ' + json.FileReferences.UserData);
                    errors++;
                }
            }
        }

        if (errors == 0)
        {
            Sys.println("OK: All references valid");
        }
        else
        {
            Sys.println('FAILED: $errors missing file(s)');
            Sys.exit(1);
        }
    }

    // ===== Internal =====

    /**
     * Sanitizes a model3.json name into a valid Haxe identifier.
     * Replaces non-[A-Za-z0-9_] chars with `_`, prefixes `_` if starts with digit,
     * deduplicates by appending `_2`, `_3`, etc.
     */
    static function sanitizeName(name:String, used:Map<String, Bool>):String
    {
        var safe = new StringBuf();
        for (i in 0...name.length)
        {
            var c = name.charAt(i);
            var code = name.charCodeAt(i);
            var isAlpha = (code >= 65 && code <= 90) || (code >= 97 && code <= 122);
            var isDigit = code >= 48 && code <= 57;
            if (isAlpha || isDigit || c == "_")
            {
                safe.add(c);
            }
            else
            {
                safe.add("_");
            }
        }
        var result = safe.toString();
        var firstCode = result.length > 0 ? result.charCodeAt(0) : 0;
        if (firstCode >= 48 && firstCode <= 57)
        {
            result = "_" + result;
        }
        if (result == "") result = "_";

        if (used.exists(result))
        {
            var n = 2;
            while (used.exists(result + "_" + n)) n++;
            result = result + "_" + n;
        }
        used.set(result, true);
        return result;
    }
}
